// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoDismissController from "./auto_dismiss_controller"
application.register("auto-dismiss", AutoDismissController)

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import BulkPackagesController from "./bulk_packages_controller"
application.register("bulk-packages", BulkPackagesController)

import BulkRoutesController from "./bulk_routes_controller"
application.register("bulk-routes", BulkRoutesController)

import CancelledPhotosController from "./cancelled_photos_controller"
application.register("cancelled-photos", CancelledPhotosController)

import DeliveryPhotosController from "./delivery_photos_controller"
application.register("delivery-photos", DeliveryPhotosController)

import DriverAutocompleteController from "./driver_autocomplete_controller"
application.register("driver-autocomplete", DriverAutocompleteController)

import FiltersPanelController from "./filters_panel_controller"
application.register("filters-panel", FiltersPanelController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PackageStatusController from "./package_status_controller"
application.register("package-status", PackageStatusController)

import PhoneController from "./phone_controller"
application.register("phone", PhoneController)

import PhotoUploadController from "./photo_upload_controller"
application.register("photo-upload", PhotoUploadController)

import RegionCommuneController from "./region_commune_controller"
application.register("region-commune", RegionCommuneController)

import ReschedulePhotosController from "./reschedule_photos_controller"
application.register("reschedule-photos", ReschedulePhotosController)

import RouteCompleteController from "./route_complete_controller"
application.register("route-complete", RouteCompleteController)

import ScannerController from "./scanner_controller"
application.register("scanner", ScannerController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SidebarMenuController from "./sidebar_menu_controller"
application.register("sidebar-menu", SidebarMenuController)

import UserRoleController from "./user_role_controller"
application.register("user-role", UserRoleController)
